### ISSUE TITLE
problem with runing zeroserver.py - Unable to read VR Path Registry from

### ISSUE THREAD

**Issue by tomaszjacek** [fornof/blvrpy#1]
Hi there,

Do you have an idea what cause and how to fix the problem?

Thank you,
tj

G:\app\BlenderFoundation\Blender2.81>G:\app\BlenderFoundation\Blender2.81\2.81\python\bin/python G:\app\BlenderFoundation\blvrpy-master\py\server\zeroserver.py 5556

Unable to read VR Path Registry from C:\Users\stefan\AppData\Local\openvr\openvrpaths.vrpath
Traceback (most recent call last):
  File "G:\app\BlenderFoundation\blvrpy-master\py\server\zeroserver.py", line 72, in <module>
    main()
  File "G:\app\BlenderFoundation\blvrpy-master\py\server\zeroserver.py", line 10, in main
    openvr.init(openvr.VRApplication_Scene)
  File "G:\app\BlenderFoundation\Blender2.81\2.81\python\lib\site-packages\openvr\__init__.py", line 6039, in init
    initInternal2(applicationType, pStartupInfo)
  File "G:\app\BlenderFoundation\Blender2.81\2.81\python\lib\site-packages\openvr\__init__.py", line 6143, in initInternal2
    _checkInitError(error.value)
  File "G:\app\BlenderFoundation\Blender2.81\2.81\python\lib\site-packages\openvr\__init__.py", line 6025, in _checkInitError
    raise OpenVRError("%s (error number %d)" %(getVRInitErrorAsSymbol(error), error))
openvr.OpenVRError: b'VRInitError_Init_PathRegistryNotFound' (error number 110)

**Comment by fornof** [comment]
https://answers.unity.com/questions/1437621/how-do-i-solve-vr-openvr-error-openvr-failed-initi.html
Check those steps.
You can also find the last line that says the line number and google the error too.
It  only works on Windows.
It must have steam and steam vr running 
possibly steam vr has to be in beta mode ( see the link)

**Comment by fornof** [comment]
also, what are you trying to do with this script?

**Comment by tomaszjacek** [comment]
Hi,
Thank you for reply.

>also, what are you trying to do with this script?

Please look here
https://github.com/EpistasisLab/3DHeatmap
Above project is a VR for data visualization. 
And in shortcut I'm trying to check if it is possible to do data visualization vr with blender.

it must be vr in  server-client mode. big data can be accessed only on server. must be accesed from all over the world.

why is that? because data files can't be moved from server to client and typical usage examle is :   parse 50GB file, process data/do some calculation,  construc dynamic mesh which represents the data, show it and more on 3d scene.
 
So, I think best idea is to stream camera view from server to client. client can sent coordinates which are request for camera  location and rotation. also requests which data and how to visualize. Server based on requests processes data and builds 3d scene and of course sends stream  from camera view  to client.

**Comment by fornof** [comment]
that's going to have some serious lag unless you have caching - it may be better to get "proxies" - such as bounding boxes to look at, then when you're ready press a button to load that image from the server at that pitch/lat/lon/yaw  - otherwise it's not going to be the best experience. 
How's progress on checking to see if it works with openvr and such?

**Comment by tomaszjacek** [comment]
>How's progress on checking to see if it works with openvr and such?

I can programming + I know nothing about VR + I know nothing about blender = no progress for now.
I will let you know when I find something.
Thank you,
tj
